// Original synthesized engine, horn and instrumental stations. No live streams.
export class CarAudio {
 constructor(){this.enabled=false;this.radio=false;this.station='harbor';this.volume=.35;this.running=false;this.speed=0;this.throttle=false;this.notes=0;this.nextNote=0;this.voices=new Set();this.files=[];this.fileIndex=0;this.media=new Audio();this.media.preload='metadata';this.media.addEventListener('ended',()=>this.nextTrack());this.media.addEventListener('error',()=>this.message('This audio file could not play. Choose another file.'));this.bind();this.autoEnable();}
 async unlock(){if(!this.ctx){const Context=window.AudioContext||window.webkitAudioContext;if(!Context)throw Error('Web Audio is unavailable in this browser.');this.ctx=new Context();this.master=this.ctx.createGain();this.master.gain.value=this.volume;const limiter=this.ctx.createDynamicsCompressor();this.master.connect(limiter);limiter.connect(this.ctx.destination);this.engine=this.ctx.createGain();this.engine.gain.value=0;this.engine.connect(this.master);this.motor=[];
 for(const [type,multiple,level]of [['sawtooth',1,.05],['triangle',2,.09],['sine',.5,.12]]){const o=this.ctx.createOscillator(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();o.type=type;o.frequency.value=35*multiple;f.type='lowpass';f.frequency.value=350;g.gain.value=level;o.connect(f);f.connect(g);g.connect(this.engine);o.start();this.motor.push({o,f,multiple})}
 this.road=this.ctx.createGain();this.road.gain.value=0;const buffer=this.ctx.createBuffer(1,this.ctx.sampleRate*2,this.ctx.sampleRate),data=buffer.getChannelData(0);let prev=0;for(let i=0;i<data.length;i++){prev=(prev+Math.random()*.04-.02)/1.02;data[i]=prev;}const noise=this.ctx.createBufferSource();noise.buffer=buffer;noise.loop=true;noise.connect(this.road);this.road.connect(this.master);noise.start();this.mediaSource=this.ctx.createMediaElementSource(this.media);this.mediaGain=this.ctx.createGain();this.mediaGain.gain.value=.65;this.mediaSource.connect(this.mediaGain);this.mediaGain.connect(this.master);this.timer=setInterval(()=>this.schedule(),50);}
 if(this.ctx.state!=='running')await this.ctx.resume();}
 message(text){document.getElementById('radioStatus').textContent=text;}
 bind(){const $=id=>document.getElementById(id);$('sound').onclick=async()=>{try{await this.unlock();this.enabled=!this.enabled;$('sound').textContent=this.enabled?'Engine on':'Engine off';$('sound').setAttribute('aria-pressed',String(this.enabled));this.update(this.running,this.speed,this.throttle)}catch(e){this.message(e.message)}};
 $('radioPower').onclick=async()=>{try{await this.unlock();this.radio=!this.radio;if(this.radio){this.nextNote=this.ctx.currentTime;this.notes=0;if(this.station==='personal')await this.playFile();}else this.stopMusic();$('radioPower').textContent=this.radio?'Radio off':'Radio on';$('radioPower').setAttribute('aria-pressed',String(this.radio));this.status()}catch(e){this.radio=false;$('radioPower').textContent='Radio on';$('radioPower').setAttribute('aria-pressed','false');this.message(e.message)}};
 $('station').onchange=async e=>{this.stopMusic();this.station=e.target.value;this.notes=0;this.nextNote=this.ctx?.currentTime||0;if(this.radio&&this.station==='personal'){try{await this.playFile()}catch(e){this.message(e.message)}}else this.status()};
 $('audioVolume').oninput=e=>{this.volume=Number(e.target.value);if(this.ctx)this.master.gain.setTargetAtTime(this.volume,this.ctx.currentTime,.04);$('audioVolumeValue').textContent=Math.round(this.volume*100)+'%'};
 $('musicFiles').onchange=e=>{this.stopMusic();for(const item of this.files)URL.revokeObjectURL(item.url);this.files=[...e.target.files].filter(f=>f.type.startsWith('audio/')||/\.(mp3|wav|m4a|ogg|flac|aac)$/i.test(f.name)).map(f=>({name:f.name,url:URL.createObjectURL(f)}));this.fileIndex=0;this.station='personal';$('station').value='personal';if(this.radio)this.playFile().catch(e=>this.message(e.message));else this.message(this.files.length+' local tracks selected · press Radio on');};
 $('nextTrack').onclick=()=>{if(this.station==='personal')this.nextTrack();else{this.notes=Math.ceil(this.notes/32)*32;this.message('Next original music phrase');}};
 const horn=$('horn');horn.onpointerdown=e=>{e.preventDefault();horn.setPointerCapture(e.pointerId);this.horn(true).catch(e=>this.message(e.message))};const release=()=>this.horn(false);horn.onpointerup=release;horn.onpointercancel=release;horn.onlostpointercapture=release;
 addEventListener('keydown',e=>{if(e.code==='KeyH'&&this.running&&!e.repeat&&!/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)){e.preventDefault();this.horn(true).catch(e=>this.message(e.message))}});addEventListener('keyup',e=>{if(e.code==='KeyH')this.horn(false)});addEventListener('blur',()=>{this.horn(false);this.media.pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){this.horn(false);this.media.pause()}});
 }
 status(){this.message(!this.radio?'Radio is off':this.station==='personal'?(this.files[this.fileIndex]?.name||'Choose audio files from your device'):this.station==='harbor'?'Harbor FM · original synth instrumental':'Coast AM · original ambient instrumental')}
 stopMusic(){this.media.pause();if(this.ctx)for(const voice of this.voices){try{voice.stop()}catch{}}this.voices.clear();}
 async playFile(){if(!this.files.length){this.message('Choose audio files from your device.');return;}if(!this.ctx)await this.unlock();const file=this.files[this.fileIndex];if(this.media.src!==file.url){this.media.src=file.url;this.media.load();}if(this.running&&this.radio)await this.media.play();this.status();}
 nextTrack(){if(this.station!=='personal'||!this.files.length)return;this.media.pause();this.fileIndex=(this.fileIndex+1)%this.files.length;this.playFile().catch(e=>this.message(e.message));}
 async horn(on){if(!on){this.hornRequested=false;if(this.hornGain&&this.ctx)this.hornGain.gain.setTargetAtTime(0,this.ctx.currentTime,.025);return;}this.hornRequested=true;await this.unlock();if(!this.hornRequested||!this.running)return;if(!this.hornGain){this.hornGain=this.ctx.createGain();this.hornGain.gain.value=0;this.hornGain.connect(this.master);for(const frequency of[350,440]){const o=this.ctx.createOscillator();o.type='triangle';o.frequency.value=frequency;o.connect(this.hornGain);o.start();}}this.hornGain.gain.setTargetAtTime(.13,this.ctx.currentTime,.015);clearTimeout(this.hornTimeout);this.hornTimeout=setTimeout(()=>this.horn(false),2500);}
 // Short horn taps: two friendly ones when a drive starts, three low angry ones at a car that will not move.
 async beep(count=2,angry=false){try{await this.unlock();}catch{return;}if(!this.enabled)return;const t0=this.ctx.currentTime+.02,len=angry?.34:.11,gap=angry?.12:.09;
  for(let i=0;i<count;i++){const g=this.ctx.createGain();g.gain.value=0;g.connect(this.master);const t=t0+i*(len+gap);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(angry?.22:.13,t+.012);g.gain.setValueAtTime(angry?.22:.13,t+len-.03);g.gain.linearRampToValueAtTime(0,t+len);
   for(const f of(angry?[300,372]:[350,440])){const o=this.ctx.createOscillator();o.type='triangle';o.frequency.value=f;o.connect(g);o.start(t);o.stop(t+len+.02);o.onended=()=>{o.disconnect();};}setTimeout(()=>g.disconnect(),(t+len-this.ctx.currentTime)*1000+100);}}
 // Sound comes on with the visitor's first click or tap anywhere, so the engine is already running when they drive.
 autoEnable(){if(this.autoTried)return;this.autoTried=true;const go=async()=>{if(this.enabled||this.ctx)return;try{await this.unlock();this.enabled=true;const b=document.getElementById('sound');if(b){b.textContent='Engine on';b.setAttribute('aria-pressed','true');}this.update(this.running,this.speed,this.throttle);}catch{}};
  addEventListener('pointerdown',go,{once:true,capture:true});addEventListener('keydown',go,{once:true,capture:true});}
 update(running,speed,throttle){const changed=running!==this.running;this.running=running;this.speed=Math.abs(speed);this.throttle=throttle;if(!this.ctx)return;const t=this.ctx.currentTime,level=running&&this.enabled?1:0;this.engine.gain.setTargetAtTime(level,t,.12);this.road.gain.setTargetAtTime(level*Math.min(.25,this.speed*.009),t,.2);const gear=Math.min(5,Math.floor(this.speed/5)),rpm=850+(this.speed-gear*5)*430+(throttle?650:0);for(const {o,f,multiple}of this.motor){o.frequency.setTargetAtTime(rpm/30*multiple,t,.12);f.frequency.setTargetAtTime(250+rpm*.17,t,.12)}
 if(changed){if(!running){this.horn(false);this.stopMusic();}else{this.nextNote=t;this.notes=0;if(this.radio&&this.station==='personal')this.playFile().catch(e=>this.message(e.message));}}}
 tone(midi,t,duration,type,level){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=440*2**((midi-69)/12);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(level,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.03);this.voices.add(o);o.onended=()=>{this.voices.delete(o);o.disconnect();g.disconnect()};}
 schedule(){if(!this.ctx||this.ctx.state!=='running'||!this.running||!this.radio||this.station==='personal'||document.hidden)return;const slow=this.station==='coast',step=60/(slow?72:100)/2,roots=[45,41,48,43];if(this.nextNote<this.ctx.currentTime)this.nextNote=this.ctx.currentTime+.02;while(this.nextNote<this.ctx.currentTime+.16){const n=this.notes++,root=roots[Math.floor(n/16)%4],t=this.nextNote;if(n%8===0)for(const interval of[0,7,12,15])this.tone(root+interval,t,slow?3.5:1.8,'sine',.027);if(!slow){if(n%2===0)this.tone(root-12,t,.28,'triangle',.08);const melody=[12,19,15,22,19,15,24,19];this.tone(root+melody[n%8],t,.22,'triangle',.025);if(n%4===0)this.tone(27,t,.09,'sine',.18);}else if(n%4===2)this.tone(root+24+(n%8===2?7:3),t,1.4,'sine',.028);this.nextNote+=step;}}
}
