// Original synthesized engine, horn and instrumental stations. No live streams.
export class CarAudio {
 constructor(){this.enabled=false;this.radio=false;this.station='bop';this.volume=.35;this.running=false;this.speed=0;this.throttle=false;this.notes=0;this.nextNote=0;this.voices=new Set();this.files=[];this.fileIndex=0;this.media=new Audio();this.media.preload='metadata';this.media.addEventListener('ended',()=>this.nextTrack());this.media.addEventListener('error',()=>this.message('This audio file could not play. Choose another file.'));this.bind();this.autoEnable();}
 async unlock(){if(!this.ctx){const Context=window.AudioContext||window.webkitAudioContext;if(!Context)throw Error('Web Audio is unavailable in this browser.');this.ctx=new Context();this.master=this.ctx.createGain();this.master.gain.value=this.volume;const limiter=this.ctx.createDynamicsCompressor();this.master.connect(limiter);limiter.connect(this.ctx.destination);this.engine=this.ctx.createGain();this.engine.gain.value=0;this.engine.connect(this.master);this.motor=[];
 for(const [type,multiple,level]of [['sawtooth',1,.05],['triangle',2,.09],['sine',.5,.12]]){const o=this.ctx.createOscillator(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();o.type=type;o.frequency.value=35*multiple;f.type='lowpass';f.frequency.value=350;g.gain.value=level;o.connect(f);f.connect(g);g.connect(this.engine);o.start();this.motor.push({o,f,multiple})}
 this.road=this.ctx.createGain();this.road.gain.value=0;const buffer=this.ctx.createBuffer(1,this.ctx.sampleRate*2,this.ctx.sampleRate),data=buffer.getChannelData(0);let prev=0;for(let i=0;i<data.length;i++){prev=(prev+Math.random()*.04-.02)/1.02;data[i]=prev;}const noise=this.ctx.createBufferSource();noise.buffer=buffer;noise.loop=true;noise.connect(this.road);this.road.connect(this.master);noise.start();this.mediaSource=this.ctx.createMediaElementSource(this.media);this.mediaGain=this.ctx.createGain();this.mediaGain.gain.value=.65;this.mediaSource.connect(this.mediaGain);this.mediaGain.connect(this.master);this.timer=setInterval(()=>this.schedule(),50);}
 if(this.ctx.state!=='running')await this.ctx.resume();}
 message(text){document.getElementById('radioStatus').textContent=text;}
 bind(){const $=id=>document.getElementById(id);$('sound').onclick=async()=>{try{await this.unlock();this.enabled=!this.enabled;$('sound').textContent=this.enabled?'Engine on':'Engine off';$('sound').setAttribute('aria-pressed',String(this.enabled));this.update(this.running,this.speed,this.throttle)}catch(e){this.message(e.message)}};
 $('radioPower').onclick=async()=>{try{await this.unlock();this.radio=!this.radio;if(this.radio){this.nextNote=this.ctx.currentTime;this.notes=0;if(this.station==='personal')await this.playFile();}else this.stopMusic();$('radioPower').textContent=this.radio?'Radio off':'Radio on';$('radioPower').setAttribute('aria-pressed',String(this.radio));this.status()}catch(e){this.radio=false;$('radioPower').textContent='Radio on';$('radioPower').setAttribute('aria-pressed','false');this.message(e.message)}};
 $('station').onchange=async e=>{this.stopMusic();this.station=e.target.value;this.notes=0;this.nextNote=this.ctx?.currentTime||0;if(this.radio&&this.station==='personal'){try{await this.playFile()}catch(e){this.message(e.message)}}else this.status()};
 $('audioVolume').oninput=e=>{this.volume=Number(e.target.value);if(this.ctx)this.master.gain.setTargetAtTime(this.volume,this.ctx.currentTime,.04);$('audioVolumeValue').textContent=Math.round(this.volume*100)+'%'};
 $('nextTrack').onclick=()=>{this.notes=Math.ceil(this.notes/64)*64;this.seed=(this.seed||1)*16807%2147483647;this.message('Next tune on '+this.stationName());};
 const horn=$('horn');horn.onpointerdown=e=>{e.preventDefault();horn.setPointerCapture(e.pointerId);this.horn(true).catch(e=>this.message(e.message))};const release=()=>this.horn(false);horn.onpointerup=release;horn.onpointercancel=release;horn.onlostpointercapture=release;
 addEventListener('keydown',e=>{if(e.code==='KeyH'&&this.running&&!e.repeat&&!/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)){e.preventDefault();this.horn(true).catch(e=>this.message(e.message))}});addEventListener('keyup',e=>{if(e.code==='KeyH')this.horn(false)});addEventListener('blur',()=>{this.horn(false);this.media.pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){this.horn(false);this.media.pause()}});
 }
 stationName(){return {bop:'Bop 101',surf:'Shirley Surf',jazz:'Salt Jazz',lofi:'Night Lo-fi',harbor:'Harbor FM',coast:'Coast AM'}[this.station]||this.station;}
 status(){this.message(!this.radio?'Radio is off':this.stationName()+' · original instrumental, made by the car')}
 stopMusic(){this.media.pause();if(this.ctx)for(const voice of this.voices){try{voice.stop()}catch{}}this.voices.clear();}
 async playFile(){if(!this.files.length){this.message('Choose audio files from your device.');return;}if(!this.ctx)await this.unlock();const file=this.files[this.fileIndex];if(this.media.src!==file.url){this.media.src=file.url;this.media.load();}if(this.running&&this.radio)await this.media.play();this.status();}
 nextTrack(){if(this.station!=='personal'||!this.files.length)return;this.media.pause();this.fileIndex=(this.fileIndex+1)%this.files.length;this.playFile().catch(e=>this.message(e.message));}
 async horn(on){if(!on){this.hornRequested=false;if(this.hornGain&&this.ctx)this.hornGain.gain.setTargetAtTime(0,this.ctx.currentTime,.025);return;}this.hornRequested=true;await this.unlock();if(!this.hornRequested||!this.running)return;if(!this.hornGain){this.hornGain=this.ctx.createGain();this.hornGain.gain.value=0;this.hornGain.connect(this.master);for(const frequency of[350,440]){const o=this.ctx.createOscillator();o.type='triangle';o.frequency.value=frequency;o.connect(this.hornGain);o.start();}}this.hornGain.gain.setTargetAtTime(.13,this.ctx.currentTime,.015);clearTimeout(this.hornTimeout);this.hornTimeout=setTimeout(()=>this.horn(false),2500);}
 // Short horn taps: two friendly ones when a drive starts, three low angry ones at a car that will not move.
 async beep(count=2,angry=false){try{await this.unlock();}catch{return;}if(!this.enabled)return;const t0=this.ctx.currentTime+.02,len=angry?.34:.11,gap=angry?.12:.09;
  for(let i=0;i<count;i++){const g=this.ctx.createGain();g.gain.value=0;g.connect(this.master);const t=t0+i*(len+gap);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(angry?.22:.13,t+.012);g.gain.setValueAtTime(angry?.22:.13,t+len-.03);g.gain.linearRampToValueAtTime(0,t+len);
   for(const f of(angry?[300,372]:[350,440])){const o=this.ctx.createOscillator();o.type='triangle';o.frequency.value=f;o.connect(g);o.start(t);o.stop(t+len+.02);o.onended=()=>{o.disconnect();};}setTimeout(()=>g.disconnect(),(t+len-this.ctx.currentTime)*1000+100);}}
 // Sound comes on with the visitor's first click or tap anywhere, so the engine is already running when they drive.
 autoEnable(){if(this.autoTried)return;this.autoTried=true;const go=async()=>{if(this.enabled||this.ctx)return;try{await this.unlock();this.enabled=true;const b=document.getElementById('sound');if(b){b.textContent='Engine on';b.setAttribute('aria-pressed','true');}this.update(this.running,this.speed,this.throttle);}catch{}};
  addEventListener('pointerdown',go,{once:true,capture:true});addEventListener('keydown',go,{once:true,capture:true});}
 update(running,speed,throttle){const changed=running!==this.running;this.running=running;this.speed=Math.abs(speed);this.throttle=throttle;if(!this.ctx)return;const t=this.ctx.currentTime,level=running&&this.enabled?1:0;this.engine.gain.setTargetAtTime(level,t,.12);this.road.gain.setTargetAtTime(level*Math.min(.25,this.speed*.009),t,.2);const gear=Math.min(5,Math.floor(this.speed/5)),rpm=850+(this.speed-gear*5)*430+(throttle?650:0);for(const {o,f,multiple}of this.motor){o.frequency.setTargetAtTime(rpm/30*multiple,t,.12);f.frequency.setTargetAtTime(250+rpm*.17,t,.12)}
 if(changed){if(!running){this.horn(false);this.stopMusic();}else{this.nextNote=t;this.notes=0;if(this.radio&&this.station==='personal')this.playFile().catch(e=>this.message(e.message));}}}
 tone(midi,t,duration,type,level){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=440*2**((midi-69)/12);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(level,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.03);this.voices.add(o);o.onended=()=>{this.voices.delete(o);o.disconnect();g.disconnect()};}
 noise(){if(!this.noiseBuffer){const b=this.ctx.createBuffer(1,this.ctx.sampleRate,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;this.noiseBuffer=b;}return this.noiseBuffer;}
 kick(t,level=.5,decay=.16){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.frequency.setValueAtTime(150,t);o.frequency.exponentialRampToValueAtTime(42,t+.09);g.gain.setValueAtTime(level,t);g.gain.exponentialRampToValueAtTime(.001,t+decay);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+decay+.02);}
 snare(t,level=.22,decay=.14){const n=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();n.buffer=this.noise();f.type='bandpass';f.frequency.value=1900;f.Q.value=.8;g.gain.setValueAtTime(level,t);g.gain.exponentialRampToValueAtTime(.001,t+decay);n.connect(f);f.connect(g);g.connect(this.master);n.start(t);n.stop(t+decay+.02);const o=this.ctx.createOscillator(),g2=this.ctx.createGain();o.frequency.value=185;g2.gain.setValueAtTime(level*.6,t);g2.gain.exponentialRampToValueAtTime(.001,t+.07);o.connect(g2);g2.connect(this.master);o.start(t);o.stop(t+.1);}
 hat(t,level=.07,decay=.035,freq=7500){const n=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();n.buffer=this.noise();f.type='highpass';f.frequency.value=freq;g.gain.setValueAtTime(level,t);g.gain.exponentialRampToValueAtTime(.001,t+decay);n.connect(f);f.connect(g);g.connect(this.master);n.start(t);n.stop(t+decay+.02);}
 chordTone(midi,t,dur,level,type='triangle',cutoff=1800){const o=this.ctx.createOscillator(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();o.type=type;o.frequency.value=440*2**((midi-69)/12);f.type='lowpass';f.frequency.value=cutoff;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(level,t+.02);g.gain.setTargetAtTime(0,t+dur*.6,dur*.18);o.connect(f);f.connect(g);g.connect(this.master);o.start(t);o.stop(t+dur+.1);this.voices.add(o);o.onended=()=>{this.voices.delete(o);o.disconnect();g.disconnect();};}
 rnd(n){this.seed=((this.seed||7)*16807+n*2654435761)%2147483647;return (this.seed%1000)/1000;}
 // Each station is a 16th-note pattern over a chord loop. All original, all synthesised here; nothing streamed.
 STATIONS(){return {
  bop:{bpm:122,swing:0,chords:[[48,52,55,59],[43,47,50,55],[45,48,52,55],[41,45,48,52]],step:(n,t,c,root)=>{const b=n%16;
   if(b===0||b===8||b===10)this.kick(t,.5);if(b===4||b===12)this.snare(t,.2);if(b%2===0)this.hat(t,b%4===2?.09:.05);
   if(b%2===0)this.tone(root-12+(b===14?7:0),t,.2,'sawtooth',.06);
   if(b===0||b===6)for(const m of c)this.chordTone(m+12,t,.5,.035,'triangle',2200);
   const lead=[0,4,7,12,7,4,0,-5];if(b%2===1&&this.rnd(n)>.35)this.tone(root+24+lead[(n>>1)%8]+(this.rnd(n+1)>.8?2:0),t,.16,'square',.028);}},
  surf:{bpm:168,swing:0,chords:[[45,48,52],[45,48,52],[41,45,48],[43,47,50]],step:(n,t,c,root)=>{const b=n%16;
   if(b===0||b===6||b===8||b===14)this.kick(t,.48,.12);if(b===4||b===12)this.snare(t,.24,.12);this.hat(t,b%2?.045:.08,.03,8500);
   if(b%2===0)this.tone(root-12+[0,0,7,7,12,7,5,3][b/2],t,.13,'sawtooth',.07);
   if(b===0||b===8)for(const m of c)this.chordTone(m+12,t,.35,.03,'sawtooth',1600);
   const riff=[0,3,5,7,10,7,5,3,0,-2,0,3,7,10,12,10];if(b%2===0||this.rnd(n)>.5)this.tone(root+24+riff[(n>>1)%16],t,.11,'square',.03);}},
  jazz:{bpm:134,swing:.33,chords:[[48,52,55,59],[45,48,52,55],[50,53,57,60],[43,47,50,53]],step:(n,t,c,root)=>{const b=n%16;
   if(b%4===0)this.hat(t,.06,.22,6000);if(b%4===3)this.hat(t,.04,.08,6500);if(b===4||b===12)this.hat(t,.05,.05,9000);
   if(b%4===0){const walk=[0,4,7,9,12,9,7,5,0,2,4,5,7,6,5,2];this.tone(root-12+walk[(n>>2)%16],t,.42,'triangle',.11);}
   if(b===6||b===13||(b===2&&this.rnd(n)>.5))for(const m of c)this.chordTone(m+12,t,.28,.03,'triangle',2400);
   const pent=[0,3,5,7,10,12,15,17];if(b%2===0&&this.rnd(n)>.55)this.tone(root+24+pent[Math.floor(this.rnd(n+3)*8)],t,.22,'sine',.045);}},
  lofi:{bpm:74,swing:.2,chords:[[45,48,52,55,59],[41,45,48,52,55],[43,47,50,53,57],[45,48,52,55,59]],step:(n,t,c,root)=>{const b=n%16;
   if(b===0||b===10)this.kick(t,.42,.2);if(b===4||b===12)this.snare(t,.13,.16);if(b%2===0)this.hat(t,.035,.03,9000);
   if(b===0||b===7)for(const m of c)this.chordTone(m,t,1.4,.05,'triangle',900);
   if(b===0||b===8||b===11)this.tone(root-24,t,.6,'sine',.12);
   if(b===2||b===14){if(this.rnd(n)>.5)this.tone(root+24+[0,2,3,7,10][Math.floor(this.rnd(n+1)*5)],t,.5,'sine',.035);}
   if(b===0)this.hat(t,.012,.9,3000);}},
  harbor:{bpm:100,swing:0,chords:[[45,52,57,60],[41,48,53,56],[48,55,60,63],[43,50,55,58]],step:(n,t,c,root)=>{const b=n%16;
   if(b%8===0)for(const m of c)this.tone(m,t,1.8,'sine',.027);if(b%2===0)this.tone(root-12,t,.28,'triangle',.08);
   const melody=[12,19,15,22,19,15,24,19];this.tone(root+melody[(n>>1)%8],t,.22,'triangle',.025);if(b%4===0)this.tone(27,t,.09,'sine',.18);}},
  coast:{bpm:72,swing:0,chords:[[45,52,57,60],[41,48,53,56],[48,55,60,63],[43,50,55,58]],step:(n,t,c,root)=>{const b=n%16;
   if(b===0)for(const m of c)this.tone(m,t,3.5,'sine',.027);if(b===2||b===10)this.tone(root+24+(b===2?7:3),t,1.4,'sine',.028);}},
 };}
 schedule(){if(!this.ctx||this.ctx.state!=='running'||!this.running||!this.radio||document.hidden)return;const st=this.STATIONS()[this.station]||this.STATIONS().bop,step=60/st.bpm/4;
  if(this.nextNote<this.ctx.currentTime)this.nextNote=this.ctx.currentTime+.02;
  while(this.nextNote<this.ctx.currentTime+.18){const n=this.notes++,bar=Math.floor(n/16),c=st.chords[bar%st.chords.length],root=c[0];let t=this.nextNote;if(st.swing&&n%2===1)t+=step*st.swing;st.step(n,t,c,root);this.nextNote+=step;}}
}
