import {houseStop,houseView} from './frontage.js';
import {sedan} from './ambient.js'
import {carKit} from './car-kit.js';
import {AutoCruise} from './auto-cruise.js';
import * as THREE from 'three';
import {rigWheels,updateWheels} from './wheel-rig.js';
import {CarAudio} from './car-audio.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {DRACOLoader} from './vendor/DRACOLoader.js';
import {RoadNetwork,DrivingState} from './driving-physics.js';
export class Driving {
 constructor({scene,camera,controls,world,heightAt,onEnter,onExit,collisionMeshes=[]}){Object.assign(this,{scene,camera,controls,world,heightAt,onEnter,onExit,collisionMeshes});this.cars=new Map();this.carType='ferrari';this.paintColor='#b72326';this.audio=new CarAudio();this.cameraRay=new THREE.Raycaster();this.state=new DrivingState(new RoadNetwork(world.roads,world.buildings));this.cruise=new AutoCruise(this.state.network);this.input={};this.active=false;this.view='chase';this.lookYaw=0;this.lookTarget=null;this.model=null;this.paused=false;this.lastHud=0;this.wheels=[];this.minimap=document.getElementById('minimap').getContext('2d');this.bind();}
 async goForDrive(x,z){await this.enter(x,z);if(this.active)this.cruise.start(this.state);}
 async enter(x,z,preferred=null){const button=document.getElementById('drive');button.disabled=true;button.textContent='Preparing car…';try{if(!this.model){const draco=new DRACOLoader().setDecoderPath('./vendor/draco/');const loader=new GLTFLoader().setDRACOLoader(draco);const gltf=await loader.loadAsync('./assets/car.glb');this.model=gltf.scene;this.cars.set('ferrari',this.model);this.model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});this.wheels=rigWheels(this.model);const box=new THREE.Box3().setFromObject(this.model);this.model.position.y=-box.min.y;this.vehicle=new THREE.Group();this.vehicle.rotation.order="YXZ";this.vehicle.add(this.model);this.scene.add(this.vehicle);this.setPaint(this.paintColor);draco.dispose();}
 this.cruise.stop();this.state.spawn(x,z,preferred);this.setLook(0);this.active=true;this.audio.beep(2);this.paused=false;this.controls.enabled=false;this.controls.autoRotate=false;this.vehicle.visible=true;this.input={};this.onEnter();document.body.classList.add('driving');document.body.classList.toggle('cockpit-view',this.view==='interior');document.getElementById('drivehud').hidden=false;document.getElementById('pauseDrive').textContent='Pause';this.update(0,performance.now(),true);
 }catch(e){document.getElementById('searchstatus').textContent='The car could not load. '+e.message;console.error(e)}finally{button.disabled=false;button.textContent='Drive here';}}
 exit(){if(!this.active)return;this.setLook(0);this.camera.fov=48;this.camera.updateProjectionMatrix();this.cruise.stop();this.active=false;this.audio.update(false,0,false);this.input={};this.vehicle.visible=false;this.controls.enabled=true;this.controls.target.set(this.state.x,this.heightAt(this.state.x,this.state.z),this.state.z);this.camera.position.set(this.state.x+80,this.controls.target.y+100,this.state.z+120);this.controls.update();document.body.classList.remove('driving','cockpit-view');document.getElementById('drivehud').hidden=true;this.onExit();}
 async inspectHouse(h){
  const stop=houseStop(h,this.state.network);if(!stop)return null;
  await this.enter(stop.x,stop.z,stop.segment);if(!this.active)return null;
  this.pause(true);
  const b=this.world.buildings.find(b=>b.id===h.buildingId),points=b?.rings?.flat()||[];
  const extent=points.length?Math.hypot(Math.max(...points.map(p=>p[0]))-Math.min(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))-Math.min(...points.map(p=>p[1]))):16;
  const view=houseView(h,this.state.network,stop,extent);
  this.inspectionPosition=new THREE.Vector3(view.x,this.heightAt(view.x,view.z)+2.5,view.z);
  this.lookTarget=new THREE.Vector3(h.center[0],this.heightAt(...h.center)+Math.max(2,h.height*.42),h.center[1]);
  this.inspectedAddress=h.address;this.inspectionMatched=stop.matched;
  document.querySelectorAll('[data-look]').forEach(b=>b.setAttribute('aria-pressed','false'));
  this.update(0,performance.now(),true);return stop;
 }
 setLook(yaw){this.lookTarget=null;this.lookYaw=Math.max(-Math.PI,Math.min(Math.PI,yaw));document.querySelectorAll('[data-look]').forEach(b=>b.setAttribute('aria-pressed',String(Math.abs(Number(b.dataset.look)-this.lookYaw)<.01)));}
 bind(){document.querySelectorAll('[data-look]').forEach(b=>b.onclick=()=>this.setLook(Number(b.dataset.look)));const map={KeyW:'accel',ArrowUp:'accel',KeyS:'reverse',ArrowDown:'reverse',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',Space:'brake'};
 addEventListener('keydown',e=>{if(!this.active||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.code==='Escape'){this.exit();return;}if(e.code==='KeyQ'){e.preventDefault();this.setLook(Math.PI/2);}if(e.code==='KeyE'){e.preventDefault();this.setLook(-Math.PI/2);}if(e.code==='KeyC'&&!e.repeat)this.toggleCamera();if(e.code==='KeyR'&&!e.repeat)this.reset();if(map[e.code]){this.cruise.stop();if(this.paused)this.pause(false);e.preventDefault();this.input[map[e.code]]=true}});
 addEventListener('keyup',e=>{if(e.code==='KeyQ'||e.code==='KeyE')this.setLook(0);if(map[e.code])this.input[map[e.code]]=false});addEventListener('blur',()=>{this.input={};if(this.active)this.pause(true)});document.addEventListener('visibilitychange',()=>{if(document.hidden){this.input={};if(this.active)this.pause(true)}});
 /* Phones: no pedals. Touch the road to go, slide sideways to steer, let go to coast.
   The layer sits over the 3D view and under the HUD, so the buttons still work. */
 if((matchMedia('(pointer:coarse)').matches||new URLSearchParams(location.search).has('touch'))&&!document.getElementById('touchDrive')){const layer=document.createElement('div');layer.id='touchDrive';layer.innerHTML='<span class="hint">Hold the road to drive · slide to steer</span>';document.body.append(layer);let x0=null,pid=null;
  const steer=x=>{this.input.steerAxis=Math.max(-1,Math.min(1,-(x-x0)/190));};   /* a thumb travels ~150px for full lock; the physics already softens lock with speed */
  layer.addEventListener('pointerdown',e=>{if(!this.active)return;e.preventDefault();try{layer.setPointerCapture(e.pointerId);}catch(_){}pid=e.pointerId;x0=e.clientX;this.cruise.stop();if(this.paused)this.pause(false);this.input.accel=true;this.input.steerAxis=0;layer.classList.add('held');document.body.classList.add('touched');},{passive:false});
  layer.addEventListener('pointermove',e=>{if(e.pointerId!==pid||x0===null)return;steer(e.clientX);});
  const release=e=>{if(e&&e.pointerId!==pid)return;pid=null;x0=null;this.input.accel=false;this.input.steerAxis=undefined;layer.classList.remove('held');};
  window.__drive=this;layer.addEventListener('pointerup',release);layer.addEventListener('pointercancel',release);layer.addEventListener('lostpointercapture',release);}
 document.querySelectorAll('[data-pedal]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();try{b.setPointerCapture(e.pointerId);}catch(_){}this.cruise.stop();if(this.paused)this.pause(false);this.input[b.dataset.pedal]=true;b.classList.add('held')});const release=()=>{this.input[b.dataset.pedal]=false;b.classList.remove('held')};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release)});
 document.getElementById('minimap').addEventListener('click',e=>{const r=e.target.getBoundingClientRect();const x=this.state.x+((e.clientX-r.left)/r.width*180-90)/.4,z=this.state.z+((e.clientY-r.top)/r.height*180-90)/.4;this.enter(x,z);});
 document.getElementById('autoDrive').onclick=()=>{if(this.cruise.active){this.cruise.stop();return;}this.pause(false);this.cruise.start(this.state);};
 document.getElementById('carChoice').onchange=e=>this.selectCar(e.target.value);document.getElementById('paintColor').oninput=e=>this.setPaint(e.target.value);
 document.getElementById('faceLegal').onclick=()=>this.reset();
 document.getElementById('exitDrive').onclick=()=>this.exit();document.getElementById('resetCar').onclick=()=>this.reset();document.getElementById('driveCamera').onclick=()=>this.toggleCamera();document.getElementById('pauseDrive').onclick=()=>this.pause(!this.paused);
 }
 setPaint(color){this.paintColor=color;if(!this.model)return;this.model.traverse(o=>{if(!o.isMesh)return;for(const m of(Array.isArray(o.material)?o.material:[o.material]))if(m.name==='Body_Color'||m===this.model.userData.paint)m.color.set(color);});}
 selectCar(type){if(!this.vehicle)return;this.carType=type;this.state.performance=type==='ferrari'?{top:325/3.6,launch:8.8,power:260}:{top:180/3.6,launch:4,power:100};if(!this.cars.has(type)){if(type.startsWith('kit:')){carKit.load(type.slice(4)).then(t=>{if(this.carType!==type)return;this.cars.set(type,carKit.instance(t));this.selectCar(type);}).catch(()=>{});return;}this.cars.set(type,sedan(0,type));}this.vehicle.remove(this.model);this.model=this.cars.get(type);this.model.position.y=0;this.model.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(this.model);this.model.position.y=-bounds.min.y;this.vehicle.add(this.model);this.wheels=rigWheels(this.model);this.setPaint(this.paintColor);this.model.visible=this.view==='chase';}
 reset(){this.cruise.stop();this.state.spawn(this.state.x,this.state.z);this.input={};this.update(0,performance.now(),true)}
 pause(value){this.paused=value;if(!value){this.lookTarget=null;this.setLook(0);}this.audio.update(this.active&&!value,this.state.speed,false);this.input={};document.getElementById('pauseDrive').textContent=value?'Resume':'Pause'}
 toggleCamera(){this.view=this.view==='chase'?'hood':'chase';/* interior view retired (Pierce, 2026-09-08) */document.getElementById('driveCamera').textContent={chase:'Hood camera',hood:'Chase camera',interior:'Chase camera'}[this.view];document.body.classList.toggle('cockpit-view',this.view==='interior');}
 update(dt,time,instant=false){if(!this.active)return;if(!this.paused){let remaining=Math.min(dt,.1);while(remaining>0){const step=Math.min(remaining,1/90);if(this.cruise.active)this.cruise.update(step,this.state);else this.state.step(step,this.input);remaining-=step;}}
 this.audio.update(!this.paused,this.state.speed,!!this.input.accel||this.cruise.active);
 if(this.cruise.honk){this.cruise.honk=false;this.audio.beep(3,true);}this.glanceYaw=(this.glanceYaw||0)+((this.cruise.active?this.cruise.glance:0)-(this.glanceYaw||0))*Math.min(1,dt*4.5);
 const s=this.state,y=this.heightAt(s.x,s.z)+.14,forward=new THREE.Vector3(-Math.sin(s.yaw),0,-Math.cos(s.yaw));
 this.vehicle.position.set(s.x,y,s.z);this.vehicle.rotation.y=s.yaw;
 const front=this.heightAt(s.x+forward.x*1.3,s.z+forward.z*1.3),rear=this.heightAt(s.x-forward.x*1.3,s.z-forward.z*1.3);this.vehicle.rotation.x=THREE.MathUtils.lerp(this.vehicle.rotation.x,Math.atan2(front-rear,2.6),instant?1:1-Math.exp(-dt*8));updateWheels(this.wheels,s.speed,s.steer,this.paused?0:dt);
 const gaze=new THREE.Vector3(-Math.sin(s.yaw+this.lookYaw+this.glanceYaw),0,-Math.cos(s.yaw+this.lookYaw+this.glanceYaw));const target=this.lookTarget?.clone()||new THREE.Vector3(s.x,y+1.15,s.z).addScaledVector(gaze,30);const position=new THREE.Vector3(s.x,y,s.z).addScaledVector(this.view==='chase'?gaze:forward,this.view==='chase'?-6.8:this.view==='interior'?-.2:.8);position.y+=this.view==='chase'?2.9:this.view==='interior'?.95:1.2;if(this.view==='interior')position.add(new THREE.Vector3(-Math.cos(s.yaw),0,Math.sin(s.yaw)).multiplyScalar(.32));position.y=Math.max(position.y,this.heightAt(position.x,position.z)+1.2);
 if(this.lookTarget&&this.inspectionPosition)position.copy(this.inspectionPosition);const fov=this.lookTarget?60:48;if(this.camera.fov!==fov){this.camera.fov=fov;this.camera.updateProjectionMatrix();}this.camera.position.lerp(position,instant||this.view!=='chase'?1:1-Math.exp(-dt*6));const anchor=new THREE.Vector3(s.x,y+1.4,s.z),rayDirection=this.camera.position.clone().sub(anchor),rayLength=rayDirection.length();this.cameraRay.set(anchor,rayDirection.normalize());this.cameraRay.far=rayLength;const obstruction=this.cameraRay.intersectObjects(this.collisionMeshes,false)[0];if(obstruction&&!this.lookTarget)this.camera.position.copy(anchor).addScaledVector(rayDirection,Math.max(.7,obstruction.distance-.6));this.camera.lookAt(target);this.controls.target.copy(target);this.model.visible=this.view==='chase';
 if(time-this.lastHud>100||instant){const warning=document.getElementById('roadWarning');warning.hidden=!s.wrongWay&&!s.blocked;document.getElementById('warningTitle').textContent=s.wrongWay?'DO NOT ENTER · WRONG WAY':'ROAD EDGE';document.getElementById('warningMessage').textContent=s.wrongWay?'Wrong direction for this mapped one-way street. Steering and braking remain under your control.':'The car has reached the mapped road boundary. Reverse or reposition to continue.';document.getElementById('faceLegal').textContent=s.wrongWay?'Face permitted direction':'Reposition on road';document.getElementById('gearValue').textContent=s.speed<-.2?'R':Math.abs(s.speed)<.2?'N':'D';document.getElementById('assistValue').textContent=s.assisting?'Guiding away from edge':'Ready';document.getElementById('speed').textContent=Math.round(Math.abs(s.speed)*2.23694);document.getElementById('currentRoad').textContent=(s.road?.name||'Winthrop')+(s.road?.direction?' · ONE WAY':'');document.getElementById('distance').textContent=(s.distance/1609.344).toFixed(2)+' mi';document.getElementById('driveStatus').textContent=this.paused?(this.lookTarget?this.inspectedAddress+' · '+(this.inspectionMatched?'Resume to drive':'Nearby road · street match needs review'):'Paused'):s.assisting?'Road-edge assist':this.cruise.active?(this.cruise.note||'Automatic cruise'):s.wrongWay?'Wrong way · turn around':this.cruise.reason||(s.blocked?'Road edge · reverse or reset':s.speed<-.1?'Reverse':'Free drive');document.getElementById('autoDrive').textContent=this.cruise.active?'Take control':'Go for a drive';this.drawMap();this.lastHud=time;}
 }
 drawMap(){const ctx=this.minimap,s=this.state,size=180,scale=.4;ctx.fillStyle='#112b38';ctx.fillRect(0,0,size,size);ctx.strokeStyle='#617b86';ctx.lineWidth=2;ctx.beginPath();for(const road of this.world.roads){for(let i=1;i<road.points.length;i++){const a=road.points[i-1],b=road.points[i];if(Math.min(a[0],b[0])>s.x+250||Math.max(a[0],b[0])<s.x-250||Math.min(a[1],b[1])>s.z+250||Math.max(a[1],b[1])<s.z-250)continue;ctx.moveTo(90+(a[0]-s.x)*scale,90+(a[1]-s.z)*scale);ctx.lineTo(90+(b[0]-s.x)*scale,90+(b[1]-s.z)*scale)}}ctx.stroke();ctx.strokeStyle='#cde3dc';ctx.lineWidth=1.2;for(const road of this.world.roads)for(let i=1;i<road.points.length;i++){const d=road.directions?.[i-1];if(!d)continue;const a=road.points[i-1],b=road.points[i],len=Math.hypot(b[0]-a[0],b[1]-a[1]);if(len<24)continue;const x=90+((a[0]+b[0])/2-s.x)*scale,z=90+((a[1]+b[1])/2-s.z)*scale;if(x<5||x>175||z<5||z>175)continue;const dx=(b[0]-a[0])/len*d,dz=(b[1]-a[1])/len*d;ctx.beginPath();ctx.moveTo(x-dx*3-dz*3,z-dz*3+dx*3);ctx.lineTo(x+dx*3,z+dz*3);ctx.lineTo(x-dx*3+dz*3,z-dz*3-dx*3);ctx.stroke();}ctx.save();ctx.translate(90,90);ctx.rotate(-s.yaw);ctx.fillStyle='#bbecff';ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(-6,7);ctx.lineTo(6,7);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#d4e7ef';ctx.font='12px Arial';ctx.fillText('N',85,17);ctx.fillText('100 m',10,166);ctx.fillRect(10,171,40,2);}
}
